import { Transaction, ExchangeName } from '../types.ts';

const DAY_MS = 86400000;
const USD_RATE = 1405.2;

const binanceKrwValue = (amount: number, usdtPrice: number) => amount * usdtPrice * USD_RATE;

export const generateMockTransactions = (): Transaction[] => {
  const now = Date.now();

  const txs: Transaction[] = [
    {
      id: 'deposit-1',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 120 * DAY_MS,
      type: 'DEPOSIT',
      pair: 'KRW',
      amount: 250000000,
      price: 1,
      fee: 0,
      currency: 'KRW',
      krwValue: 250000000,
    },
    {
      id: 'deposit-2',
      exchange: ExchangeName.BITHUMB,
      timestamp: now - 95 * DAY_MS,
      type: 'DEPOSIT',
      pair: 'KRW',
      amount: 80000000,
      price: 1,
      fee: 0,
      currency: 'KRW',
      krwValue: 80000000,
    },
    {
      id: 'buy-btc-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 92 * DAY_MS,
      type: 'BUY',
      pair: 'BTC/KRW',
      amount: 0.72,
      price: 94000000,
      fee: 33840,
      currency: 'BTC',
      krwValue: 67680000,
    },
    {
      id: 'buy-eth-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 88 * DAY_MS,
      type: 'BUY',
      pair: 'ETH/KRW',
      amount: 13,
      price: 4050000,
      fee: 26325,
      currency: 'ETH',
      krwValue: 52650000,
    },
    {
      id: 'buy-sol-bithumb',
      exchange: ExchangeName.BITHUMB,
      timestamp: now - 79 * DAY_MS,
      type: 'BUY',
      pair: 'SOL/KRW',
      amount: 180,
      price: 192000,
      fee: 17280,
      currency: 'SOL',
      krwValue: 34560000,
    },
    {
      id: 'buy-xrp-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 74 * DAY_MS,
      type: 'BUY',
      pair: 'XRP/KRW',
      amount: 21000,
      price: 790,
      fee: 8295,
      currency: 'XRP',
      krwValue: 16590000,
    },
    {
      id: 'buy-doge-bithumb',
      exchange: ExchangeName.BITHUMB,
      timestamp: now - 68 * DAY_MS,
      type: 'BUY',
      pair: 'DOGE/KRW',
      amount: 58000,
      price: 145,
      fee: 4205,
      currency: 'DOGE',
      krwValue: 8410000,
    },
    {
      id: 'buy-hbar-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 62 * DAY_MS,
      type: 'BUY',
      pair: 'HBAR/KRW',
      amount: 85000,
      price: 320,
      fee: 13600,
      currency: 'HBAR',
      krwValue: 27200000,
    },
    {
      id: 'buy-eth-bithumb',
      exchange: ExchangeName.BITHUMB,
      timestamp: now - 58 * DAY_MS,
      type: 'BUY',
      pair: 'ETH/KRW',
      amount: 4.8,
      price: 4180000,
      fee: 10032,
      currency: 'ETH',
      krwValue: 20064000,
    },
    {
      id: 'buy-sui-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 54 * DAY_MS,
      type: 'BUY',
      pair: 'SUI/KRW',
      amount: 6400,
      price: 1750,
      fee: 5600,
      currency: 'SUI',
      krwValue: 11200000,
    },
    {
      id: 'buy-btc-binance',
      exchange: ExchangeName.BINANCE,
      timestamp: now - 48 * DAY_MS,
      type: 'BUY',
      pair: 'BTC/USDT',
      amount: 0.22,
      price: 70000,
      fee: 15.4,
      currency: 'BTC',
      krwValue: binanceKrwValue(0.22, 70000),
      exchangeRate: USD_RATE,
    },
    {
      id: 'buy-pepe-binance',
      exchange: ExchangeName.BINANCE,
      timestamp: now - 44 * DAY_MS,
      type: 'BUY',
      pair: 'PEPE/USDT',
      amount: 950000000,
      price: 0.0000105,
      fee: 9.975,
      currency: 'PEPE',
      krwValue: binanceKrwValue(950000000, 0.0000105),
      exchangeRate: USD_RATE,
    },
    {
      id: 'buy-jup-binance',
      exchange: ExchangeName.BINANCE,
      timestamp: now - 40 * DAY_MS,
      type: 'BUY',
      pair: 'JUP/USDT',
      amount: 8500,
      price: 0.95,
      fee: 8.075,
      currency: 'JUP',
      krwValue: binanceKrwValue(8500, 0.95),
      exchangeRate: USD_RATE,
    },
    {
      id: 'buy-ada-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 36 * DAY_MS,
      type: 'BUY',
      pair: 'ADA/KRW',
      amount: 30000,
      price: 680,
      fee: 10200,
      currency: 'ADA',
      krwValue: 20400000,
    },
    {
      id: 'sell-ada-upbit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 18 * DAY_MS,
      type: 'SELL',
      pair: 'ADA/KRW',
      amount: 30000,
      price: 760,
      fee: 11400,
      currency: 'ADA',
      krwValue: 22800000,
    },
    {
      id: 'withdraw-krw-1',
      exchange: ExchangeName.BITHUMB,
      timestamp: now - 15 * DAY_MS,
      type: 'WITHDRAWAL',
      pair: 'KRW',
      amount: 55000000,
      price: 1,
      fee: 0,
      currency: 'KRW',
      krwValue: 55000000,
    },
    {
      id: 'travel-rule-deposit',
      exchange: ExchangeName.UPBIT,
      timestamp: now - 12 * 60 * 60 * 1000,
      type: 'DEPOSIT',
      pair: 'KRW',
      amount: 10000000,
      price: 1,
      fee: 0,
      currency: 'KRW',
      krwValue: 10000000,
    },
  ];

  return txs.sort((a, b) => b.timestamp - a.timestamp);
};
